### ISSUE TITLE
Error: MAX_WRITE_OPERATIONS_PER_HOUR

### ISSUE THREAD

**Issue by YamiOdymel** [MiCottOn/DejaVue#61]
```
Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_HOUR quota.
    at firstNodeCounter (chrome-extension://jpigngmphmclcmikmcbcfplgnhlnefbp/app/assets/js/content-script.js:61:25)
    at chrome-extension://jpigngmphmclcmikmcbcfplgnhlnefbp/app/assets/js/content-script.js:68:17
```

![screen shot 2017-02-23 at 6 14 25 pm](https://cloud.githubusercontent.com/assets/7308718/23254714/f2464ec0-f9f3-11e6-9b4e-fb26364667ee.png)

**Comment by kimhjona** [comment]
hi @YamiOdymel do you by chance have a public repo of the application you were running when you received this error?
